version: '3.9'

services:
  server:
    build: .
    container_name: memity-api  
    ports:
      - "9000"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: memity-nginx
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/zerossl/
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge      